behaviors:
  FPV-Drone:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 500000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 256
    summary_freq: 30000
environment_parameters:
  Lesson:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: FPV-Drone
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 0.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: FPV-Drone
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
          require_reset: true
        value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: FPV-Drone
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
          require_reset: true
        value: 2.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: FPV-Drone
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.9
          require_reset: true
        value: 3.0
      - name: Lesson4
        value: 4.0