behaviors:
  FPV-Drone:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512   
      buffer_size: 409600     
      learning_rate: 0.00003     
      beta: 0.0003   
      epsilon: 0.2  
      lambd: 0.95
      num_epoch: 4  
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512     
      num_layers: 3     
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99     
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.05
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1024   
    summary_freq: 30000
environment_parameters:
  Lesson:
    curriculum:
      # - name: Lesson0
      #   completion_criteria:
      #     measure: reward
      #     behavior: FPV-Drone
      #     signal_smoothing: true
      #     min_lesson_length: 100
      #     threshold: 0.5
      #   value: 0.0
      # - name: Lesson1
      #   completion_criteria:
      #     measure: reward
      #     behavior: FPV-Drone
      #     signal_smoothing: true
      #     min_lesson_length: 100
      #     threshold: 0.7
      #     require_reset: true
      #   value: 1.0
      # - name: Lesson2
      #   completion_criteria:
      #     measure: reward
      #     behavior: FPV-Drone
      #     signal_smoothing: true
      #     min_lesson_length: 100
      #     threshold: 0.8
      #     require_reset: true
      #   value: 2.0
      # - name: Lesson3
      #   completion_criteria:
      #     measure: reward
      #     behavior: FPV-Drone
      #     signal_smoothing: true
      #     min_lesson_length: 100
      #     threshold: 0.9
      #     require_reset: true
      #   value: 3.0
      - name: Lesson4
        value: 4.0